"""
bundle_builder_project — embed a .bhrx.json project into the Experience
Builder as tools/experience_builder/js/project_data.js.

Why: the builder is a no-server file:// page, and browsers refuse fetch() of
local JSON there — but they DO load <script> tags. Bundling the project as a
script makes it appear automatically when index.html is opened, no manual
Open needed. Audio/video FILES still can't be bundled (browsers cannot open
local files by path); the one-time Media re-link / Sounds 📁 link-folder
persists via IndexedDB handles afterwards.

The bundle carries a stamp; the builder loads the bundle when the stamp is
new (fresh import wins, the previous draft is backed up in localStorage) and
otherwise keeps your autosaved edits of that same bundle.

Usage:
    py -3.12 scripts/bundle_builder_project.py                       # BHR_Experience.bhrx.json
    py -3.12 scripts/bundle_builder_project.py path/to/project.json

Also run automatically by scripts/capcut_audio.py --to-builder.
"""

from __future__ import annotations

import json
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PROJECT = ROOT / "BHR_Experience.bhrx.json"
OUT_PATH = ROOT / "tools" / "experience_builder" / "js" / "project_data.js"


def write_bundle(project_path: Path, out_path: Path = OUT_PATH) -> None:
    with open(project_path, encoding="utf-8") as f:
        project = json.load(f)
    stamp = time.strftime("%Y-%m-%d %H:%M:%S")
    payload = {"stamp": stamp, "source": project_path.name, "project": project}
    js = ("/* generated by scripts/bundle_builder_project.py — do not edit.\n"
          f" * source: {project_path.name}   bundled: {stamp} */\n"
          "window.BHR_BUNDLED_PROJECT = "
          + json.dumps(payload, ensure_ascii=False)
          + ";\n")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(js)
    kb = out_path.stat().st_size / 1024
    print(f"[bundle_builder_project] {out_path.relative_to(ROOT)} "
          f"({kb:.0f} KB) from {project_path.name}")


def main() -> int:
    project = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_PROJECT
    if not project.exists():
        sys.exit(f"project not found: {project}")
    write_bundle(project)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
